### ISSUE TITLE
recommended nix-channel or nixpkgs version?

### ISSUE THREAD

**Issue by ninegua** [jyrimatti/hseverywhere#2]
I'm trying it out with latest nixpkgs-unstable on OS X 10.11.6, and running `nix-shell` in the hseverywhere directory leads to building GHC 7.8.4... kind of crazy, isn't it?

Do you think specifying a particular version of ghc and/or ghcjs (in `default.nix`) can fix this problem?

Before I did the `nix-channel --update`, I ran into some broken dependency issue in building `ghcjs`. So I thought maybe I should update the channel, and now this...

**Comment by ninegua** [comment]
well, even the latest wouldn't work. Still fails at `haddock`:

```
Configuring haddock-2.17.2...
Setup: At least the following dependencies are missing:
haddock-api ==2.17.*
builder for ‘/nix/store/88plc2m43y6b31bgxpz2628rdhnk5m3f-haddock-2.17.2.drv’ failed with exit code 1
```

**Comment by ninegua** [comment]
Looks like I'm hit by this: https://github.com/NixOS/nixpkgs/issues/17176

**Comment by jyrimatti** [comment]
Hi,
I have no idea about the stability of different nix-channels/branches or ghc/ghcjs in them...

... except that everything seems to break every now and then at least in nixpkgs master. That's why I wanted to make this project always use an explicitly specified state (in nix-revision.txt), so that it doesn't break even if you meddle with your global Nix installation.

Unfortunately I seem to have forgot to "purify" the basic shell (whoops), so running "nix-shell" used your global Nix installation. Please use "./shell.sh" to start the shell in the same revision all other scripts use. If you want to try different revision just set it in nix-revision.txt and try out the different script to see if it works.

Does this solve your problem, even though it doesn't directly answer your question about recommended channel/revision?

**Comment by ninegua** [comment]
Thanks! I'm trying it out...

**Comment by ninegua** [comment]
Yes, it worked! Thanks a bunch! This is a very cool project, keep it coming!
